# Generated by Django 4.2.3 on 2023-07-21 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='tax_rate',
            field=models.FloatField(default=0.0, help_text='Enter in % only'),
        ),
    ]
