# Generated by Django 4.2.3 on 2023-07-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productvariant',
            table='product_variants',
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviwes',
        ),
    ]
