# Generated by Django 4.2.3 on 2023-07-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productvariant_table_alter_review_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numReviews',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterModelTable(
            name='review',
            table='reviews',
        ),
    ]
