version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/ecommerce_apis_with_sequelize
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: pipelines/integrations-deployment-pre-post.sh
