# Generated by Django 4.2.3 on 2023-07-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={},
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banners',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brands',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='childcategory',
            table='childcategories',
        ),
        migrations.AlterModelTable(
            name='subcategory',
            table='subcategories',
        ),
    ]
