# Generated by Django 4.2.3 on 2023-07-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_status_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finalAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='order',
            name='taxAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
