# Generated by Django 4.2.3 on 2023-07-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_finalamount_order_taxamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancel_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
