# Generated by Django 4.2.3 on 2023-07-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_order_cancel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discountAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
