# Generated by Django 4.2.3 on 2023-08-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_discountamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellationReason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
