# Generated by Django 4.2.3 on 2023-07-18 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='productmeaserment',
            new_name='product_variant',
        ),
    ]
